version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile

    volumes:
      - ..:/app

    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ../.config/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"